# Generated by Django 6.0.2 on 2026-04-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_complaint_location_lng"),
    ]

    operations = [
    migrations.RunSQL(
        "CREATE INDEX IF NOT EXISTS idx_complaint_status ON complaints_complaint(status);",
        reverse_sql="DROP INDEX IF EXISTS idx_complaint_status;"
    ),
    migrations.RunSQL(
        "CREATE INDEX IF NOT EXISTS idx_complaint_category ON complaints_complaint(category);",
        reverse_sql="DROP INDEX IF EXISTS idx_complaint_category;"
    ),
    migrations.RunSQL(
        "CREATE INDEX IF NOT EXISTS idx_complaint_created ON complaints_complaint(created_at DESC);",
        reverse_sql="DROP INDEX IF EXISTS idx_complaint_created;"
    ),
]
