# Generated by Django 6.0.2 on 2026-06-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_alter_complaint_citizen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.CharField(
                choices=[
                    ("water", "Water"),
                    ("road", "Road"),
                    ("electricity", "Electricity"),
                    ("sanitation", "Sanitation"),
                    ("park", "Park"),
                    ("safety", "Safety"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("reported", "Reported"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="reported",
                max_length=12,
            ),
        ),
    ]
