CATEGORY_TRAINING_DATA = [

    # --------------------------------------------------------
    # road complaints
    # Keywords the model should learn: pothole, road, street,
    # pavement, crack, broken road, footpath, traffic, bridge
    # --------------------------------------------------------
    ("There is a large pothole on the main road near the market", "road"),
    ("The road in our neighborhood has not been repaired for months", "road"),
    ("A big crack has appeared on the highway causing accidents", "road"),
    ("The footpath near the school is completely broken", "road"),
    ("Our street is full of potholes and vehicles get damaged", "road"),
    ("The bridge near the river has cracks and feels unsafe", "road"),
    ("road construction debris has been left blocking the street for weeks", "road"),
    ("The road surface is very uneven and causes accidents at night", "road"),
    ("After the rain the road collapsed and is now impassable", "road"),
    ("The main road near the temple has not been paved yet", "road"),
    ("There are dangerous potholes on the road to the hospital", "road"),
    ("The road is broken and muddy making it hard to walk", "road"),
    ("Street near my house has no pavement and is very dusty", "road"),
    ("The road divider is broken and causing traffic confusion", "road"),
    ("A large hole appeared on the road after the recent flooding", "road"),
    ("The road to the school is unpaved and children struggle daily", "road"),
    ("There is no proper road marking and accidents keep happening", "road"),
    ("The bridge connecting our village is damaged and dangerous", "road"),
    ("Construction workers left the road dug up without repairing it", "road"),
    ("The road near the bus park is full of deep potholes", "road"),
    ("Footpath bricks are broken and elderly people keep falling", "road"),
    ("The road is flooded because the drainage is blocked", "road"),
    ("Heavy vehicles have destroyed the road surface completely", "road"),
    ("The road near the river floods every rainy season", "road"),
    ("Speed breakers on the road are not painted and invisible at night", "road"),
    ("The road near the hospital is full of potholes and ambulances struggle", "road"),
    ("Heavy rain washed away part of the road and it is now dangerous", "road"),
    ("The road is so narrow and broken that two vehicles cannot pass", "road"),
    ("Road repair work started three months ago but was never finished", "road"),
    ("The culvert on our road is broken and water floods every rain", "road"),
    ("Mud from the hillside has covered the road completely", "road"),
    ("The road to our village has not been blacktopped for ten years", "road"),
    ("There is a sharp broken edge on the road that punctures tires", "road"),
    ("The sidewalk near the market is completely dug up and dangerous", "road"),
    ("A deep trench was dug for pipe work and never properly refilled", "road"),
    ("The road near the bridge floods every monsoon and blocks traffic", "road"),
    ("Broken road has caused multiple accidents in the past month", "road"),
    ("The road shoulder has eroded and vehicles fall off the edge", "road"),
    ("Our colony road has not been repaired since it was first built", "road"),
    ("The road to the cremation ground is full of potholes and unusable", "road"),


    # --------------------------------------------------------
    # water complaints
    # Keywords: water, pipe, supply, tap, leakage, shortage,
    # drinking water, contaminated, pressure, tank
    # --------------------------------------------------------
    ("There has been no water supply in our area for three days", "water"),
    ("The water pipe near our street is broken and leaking", "water"),
    ("Drinking water is contaminated and smells very bad", "water"),
    ("water pressure in our taps is very low and we cannot use it", "water"),
    ("The main water pipe burst and flooded the street", "water"),
    ("We have not received water supply for over a week now", "water"),
    ("The water coming from the tap is yellowish and dirty", "water"),
    ("There is a water leakage from the pipe near the road", "water"),
    ("Our community water tank is damaged and needs urgent repair", "water"),
    ("water supply is very irregular and sometimes we get nothing", "water"),
    ("The drinking water tastes bad and may be contaminated", "water"),
    ("A broken water pipe is wasting water and flooding the road", "water"),
    ("There is no water supply to our ward for the past five days", "water"),
    ("water comes only for thirty minutes a day which is not enough", "water"),
    ("The overhead water tank in our area is leaking badly", "water"),
    ("Pipe joints are broken and clean water is mixing with sewage", "water"),
    ("Our tap has had no water pressure for two weeks", "water"),
    ("water meter is broken and we are being charged incorrectly", "water"),
    ("The water supply pipe is too old and bursts frequently", "water"),
    ("We have been buying drinking water because the supply is off", "water"),
    ("Muddy water is coming from the tap after the recent rain", "water"),
    ("water shortage is severe in our area especially in summer", "water"),
    ("The valve for our area water supply has been broken for days", "water"),
    ("Children are getting sick because the water is contaminated", "water"),
    ("water supply schedule is not being followed by the authority", "water"),
    ("The water tank in our area has not been cleaned for over a year", "water"),
    ("Water supply pipe runs through a garbage dump and may be contaminated", "water"),
    ("We only get water supply twice a week which is not enough", "water"),
    ("The tap water has a strong chlorine smell and is unpleasant", "water"),
    ("Water pipe near the road broke and has been leaking for five days", "water"),
    ("Our area has never had a proper water supply connection", "water"),
    ("The water distribution is unequal and some areas get more than others", "water"),
    ("Water supply was cut during construction and never restored", "water"),
    ("The community water tap is broken and water runs continuously wasted", "water"),
    ("We have no water supply in the morning when we need it most", "water"),
    ("The water pipe passes through a sewage area and smells bad", "water"),
    ("Water comes with mud and sand particles and is undrinkable", "water"),
    ("The overhead tank overflows every day wasting large amounts of water", "water"),
    ("Children have to carry water from far because local supply is broken", "water"),
    ("Water supply was promised for our area two years ago but never came", "water"),

    # --------------------------------------------------------
    # electricity complaints
    # Keywords: power, electricity, light, outage, transformer,
    # wire, pole, voltage, load shedding, blackout
    # --------------------------------------------------------
    ("There has been no electricity in our area since yesterday evening", "electricity"),
    ("The electric pole near our house is leaning dangerously", "electricity"),
    ("Power cuts are happening every few hours without any schedule", "electricity"),
    ("The transformer in our ward blew up and power is still out", "electricity"),
    ("Street lights in our area have not been working for a month", "electricity"),
    ("electricity voltage is very low and appliances keep getting damaged", "electricity"),
    ("A live electric wire is hanging on the road and is very dangerous", "electricity"),
    ("Power outage has been going on for two days without any update", "electricity"),
    ("The electricity meter is broken and giving wrong readings", "electricity"),
    ("Street light pole is broken and the area is very dark at night", "electricity"),
    ("There is frequent load shedding affecting businesses and homes", "electricity"),
    ("Sparks are coming from the electric pole near the market", "electricity"),
    ("Power supply is very unstable and fluctuates constantly", "electricity"),
    ("The main power line to our area was damaged in the storm", "electricity"),
    ("We have had no electricity for three days after the landslide", "electricity"),
    ("Electric wires are too low and touching tree branches dangerously", "electricity"),
    ("Power disruption is happening every night in our locality", "electricity"),
    ("The fuse box on the pole keeps blowing and nobody fixes it", "electricity"),
    ("electricity bills are very high compared to what we consume", "electricity"),
    ("Night lighting in the park is broken and the area is unsafe", "electricity"),
    ("Unscheduled power cuts are affecting students and their studies", "electricity"),
    ("The electricity pole in the street is rusted and about to fall", "electricity"),
    ("There is a short circuit issue in our neighborhood power supply", "electricity"),
    ("Power restoration after outage takes too long in our area", "electricity"),
    ("Our area experiences blackouts every time it rains heavily", "electricity"),
    ("The streetlight outside our house has been broken for three months", "electricity"),
    ("Broken streetlight makes the road very dark and unsafe at night", "electricity"),
    ("Street light near the school is not working and students are scared", "electricity"),
    ("The electric meter box is damaged and exposed to rain", "electricity"),
    ("Power goes out every time it rains even lightly in our area", "electricity"),
    ("The electricity pole was hit by a vehicle and is now unstable", "electricity"),
    ("Loose electric wires are hanging near the children playground", "electricity"),
    ("Our area has had no power for four days after the storm", "electricity"),
    ("The transformer serving our ward needs replacement it is very old", "electricity"),
    ("Electric sparks were seen from the pole near the market last night", "electricity"),
    ("The electricity department does not respond to our complaints at all", "electricity"),
    ("Power supply is cut without notice and comes back unpredictably", "electricity"),
    ("The street has ten lights but eight of them are not working", "electricity"),
    ("The electric pole is cracked at the base and could fall any time", "electricity"),
    ("Load shedding schedule is not followed and we have no power all day", "electricity"),

    # --------------------------------------------------------
    # sanitation complaints
    # Keywords: garbage, waste, trash, drainage, sewer, smell,
    # dirty, clean, toilet, hygiene, dump, littering
    # --------------------------------------------------------
    ("Garbage has not been collected from our area for two weeks", "sanitation"),
    ("There is a large pile of trash near the school gate", "sanitation"),
    ("The drainage near our house is completely blocked and overflowing", "sanitation"),
    ("Sewage water is flowing on the road due to blocked drain", "sanitation"),
    ("People are dumping garbage on the roadside openly", "sanitation"),
    ("The public toilet near the market is very dirty and unusable", "sanitation"),
    ("There is a very bad smell coming from the open drain nearby", "sanitation"),
    ("Waste is being burned near the residential area causing smoke", "sanitation"),
    ("The garbage collection vehicle has not come in over a week", "sanitation"),
    ("There is no proper waste disposal facility in our ward", "sanitation"),
    ("Stray animals are spreading garbage all over the street", "sanitation"),
    ("Open defecation is happening near the river by the settlement", "sanitation"),
    ("The drain is clogged and sewage is entering homes during rain", "sanitation"),
    ("Hospital waste is being dumped in the open near our community", "sanitation"),
    ("The public dustbin is overflowing and nobody is clearing it", "sanitation"),
    ("Dirty water from the drain is spreading disease in the area", "sanitation"),
    ("No sanitation workers have visited our area this entire month", "sanitation"),
    ("The sewer line is broken and waste is coming up on the road", "sanitation"),
    ("Children are playing near open waste which is a health hazard", "sanitation"),
    ("Market area waste is never properly cleaned causing hygiene issues", "sanitation"),
    ("Dead animals are lying on the road and nobody is removing them", "sanitation"),
    ("The community toilet has no water supply and is not maintained", "sanitation"),
    ("Plastic waste is being thrown into the river near our area", "sanitation"),
    ("The drain cleaning was promised months ago but never happened", "sanitation"),
    ("Our neighborhood smells very bad due to rotting uncollected waste", "sanitation"),
    ("Garbage truck comes only once a month and waste piles up badly", "sanitation"),
    ("The open drain near our house is never cleaned and always smells", "sanitation"),
    ("Waste water from the market flows directly onto the street", "sanitation"),
    ("There is no garbage collection system in our ward at all", "sanitation"),
    ("The public toilet near the bus stand has been locked for weeks", "sanitation"),
    ("Meat waste from the butcher shop is thrown on the road openly", "sanitation"),
    ("The drain behind our homes is completely filled with solid waste", "sanitation"),
    ("Flies and mosquitoes are breeding in the uncollected garbage nearby", "sanitation"),
    ("The road sweeper vehicle has not visited our street in a month", "sanitation"),
    ("Construction waste has been dumped on the road and never removed", "sanitation"),
    ("The public toilet has no door and no water and is completely unusable", "sanitation"),
    ("Garbage is piling near the school gate and children are getting sick", "sanitation"),
    ("The drain is so blocked that even light rain causes flooding", "sanitation"),
    ("Chemical waste is being dumped into the local drain by a factory", "sanitation"),
    ("Our area has no proper drainage and water stagnates after every rain", "sanitation"),


    # --------------------------------------------------------
    # park complaints
    # Keywords: park, bench, wall, building, sign, government,
    # playground, vandalism, broken, public space, fence
    ("The park bench near our house is completely broken", "park"),
    ("The playground equipment for children is broken and dangerous", "park"),
    ("The boundary wall of the public park has collapsed", "park"),
    ("The public water fountain in the park is not working", "park"),
    ("Vandals have destroyed the lights in the public garden", "park"),
    ("The gate to the public park is broken and does not close", "park"),
    ("Children playground swings are rusted and broken", "park"),
    ("Benches in the public garden are all broken or missing", "park"),
    ("The public garden has no lights and is unsafe at night", "park"),
    ("The public swimming pool facility has been closed for months", "park"),
    ("The park has no proper fencing and animals enter freely", "park"),
    ("Grass in the public park has not been mowed for months", "park"),
    ("The walking track in the park is broken and uneven", "park"),
    ("Public garden dustbins are overflowing and nobody cleans them", "park"),
    ("The children play area in the park has no shade and is unsafe", "park"),
    ("Park lights are broken and people feel unsafe walking at night", "park"),
    ("The park fountain has been dry for months and looks abandoned", "park"),
    ("Playground slide is broken and children have gotten hurt", "park"),
    ("The public garden gate is locked and residents cannot enter", "park"),
    ("Trees in the park are dead and nobody is maintaining them", "park"),
    ("The park has no drinking water facility for visitors", "park"),
    ("Public garden is being used for dumping garbage illegally", "park"),
    ("The park path is flooded during rain because of poor drainage", "park"),
    ("Streetlights inside the park have been broken for two months", "park"),
    ("The park wall is damaged and stray animals keep entering", "park"),
    ("The park has no proper fencing and stray animals enter freely", "park"),
    ("Grass in the public park has not been mowed for months", "park"),
    ("The walking track in the park is broken and uneven", "park"),
    ("The children play area in the park has no shade and gets very hot", "park"),
    ("Playground slide is broken and a child got hurt last week", "park"),
    ("The public garden gate is always locked and residents cannot enter", "park"),
    ("Trees in the park are dead and nobody is maintaining them", "park"),
    ("The park has no drinking water facility for visitors", "park"),
    ("Public garden is being used for dumping garbage illegally", "park"),
    ("The park path floods during rain because of poor drainage", "park"),
    ("The park wall is damaged and outsiders are misusing the space", "park"),
    ("The community garden has been taken over by weeds and is unusable", "park"),
    ("Park benches are so broken that nobody can sit on them anymore", "park"),
    ("The public garden has no toilet facility for visitors", "park"),
    ("Children cannot play in the park because equipment is all damaged", "park"),


     # SAFETY complaints
    ("There is no street lighting and the area feels unsafe at night", "safety"),
    ("Stray dogs are attacking people near the market area", "safety"),
    ("A broken manhole is open on the road and children could fall in", "safety"),
    ("The area near the river has no safety railing and is dangerous", "safety"),
    ("There have been multiple robberies in our area at night", "safety"),
    ("The school zone has no speed limit signs and children are at risk", "safety"),
    ("A large crack in the road is invisible at night and causes falls", "safety"),
    ("The public staircase has no handrail and elderly people fall", "safety"),
    ("The road near the school has no zebra crossing and children are at risk", "safety"),
    ("There is no speed limit enforcement near the hospital zone", "safety"),
    ("An open electrical panel box is on the street accessible to anyone", "safety"),
    ("The river bank has no railing and children play near it unsafely", "safety"),
    ("Street gangs have been gathering near our area and residents feel unsafe", "safety"),
    ("The road has no reflectors or markings and night accidents happen often", "safety"),
    ("Stray dogs have bitten three children in our area this month", "safety"),
    ("The building under construction has no safety barriers around it", "safety"),
    ("There is no CCTV or lighting in the underpass and it feels dangerous", "safety"),
    ("The school has no boundary wall and strangers can enter freely", "safety"),
    ("Motorcycles drive on the footpath and pedestrians are in danger", "safety"),
    ("There is no warning sign near the dangerous curve on the highway", "safety"),
    ("The market area has no fire safety equipment and is a fire risk", "safety"),
    ("A broken glass structure near the playground is injuring children", "safety"),
    ("There is no guard or gate at the community water reservoir", "safety"),


    # other complaints
    ("I want to report a general issue in my area", "other"),
    ("There is a problem in our locality that needs attention", "other"),
    ("Something is wrong near my house but I am not sure what department", "other"),
    ("This issue does not fit any category but needs to be fixed", "other"),
    ("There is an unidentified problem affecting our community", "other"),
    ("I want to report a general issue in my area that needs attention", "other"),
    ("There is a problem in our locality but I am not sure which department", "other"),
    ("This issue does not fit any specific category but needs to be fixed", "other"),
    ("There is something wrong in our community that the municipality should know", "other"),
    ("A general complaint about the condition of our neighborhood", "other"),
    ("The local authority is not responding to any of our requests", "other"),
    ("Our ward has multiple unaddressed issues for a very long time", "other"),
    ("I am reporting a miscellaneous civic problem that needs review", "other"),
    ("The situation in our area is bad and needs government attention", "other"),
    ("There is an unresolved issue that has been ignored for months", "other"),
]



PRIORITY_TRAINING_DATA = [

    # --------------------------------------------------------
    # high priority
    # Signal words: dangerous, emergency, accident, injured,
    # collapsing, no water for days, live wire, contaminated,
    # children sick, urgent, flooding, blackout
    # --------------------------------------------------------
    ("A live electric wire is hanging on the road and people could die", "high"),
    ("The bridge is cracking and may collapse any moment it is very dangerous", "high"),
    ("Drinking water is contaminated and children in our area are getting sick", "high"),
    ("There has been no water supply for five days and it is an emergency", "high"),
    ("Sewage water is entering homes and families cannot live there", "high"),
    ("An electric pole is leaning on the road and sparks are visible", "high"),
    ("The road completely collapsed after the rain and no vehicle can pass", "high"),
    ("There is no electricity for three days and patients at home need power", "high"),
    ("The drain burst and sewage is flooding inside houses right now", "high"),
    ("A large tree fell on the road and is blocking emergency vehicles", "high"),
    ("The water pipe burst and water is flooding the street dangerously", "high"),
    ("Children fell into a broken manhole on the road yesterday", "high"),
    ("Hospital waste is dumped openly near homes causing serious health risk", "high"),
    ("People have been injured due to the broken road near the market", "high"),
    ("The building wall is cracking and may fall on passing pedestrians", "high"),
    ("water supply has been completely cut off for an entire week", "high"),
    ("Electrical short circuit caused a small fire near the transformer", "high"),
    ("A massive pothole caused a motorcycle accident last night", "high"),
    ("Sewage smell is so strong people are getting respiratory problems", "high"),
    ("The footpath collapsed and an elderly person fell into the ditch", "high"),
    ("A child was injured by falling into an open drain yesterday", "high"),
    ("The road collapsed completely and emergency vehicles cannot pass", "high"),
    ("Raw sewage is overflowing into the drinking water supply", "high"),
    ("A gas leak smell is coming from the road near our houses", "high"),
    ("The electric pole fell on the road and is blocking all traffic", "high"),
    ("Flood water entered our homes and we need urgent help", "high"),
    ("The water supply has been contaminated and people are vomiting", "high"),
    ("A large portion of the hillside is sliding toward our houses", "high"),
    ("The bridge is shaking badly when vehicles cross it", "high"),
    ("There is a live wire on the wet road and nobody has cordoned it off", "high"),

    # --------------------------------------------------------
    # medium priority
    # Signal words: not working, irregular, damaged, broken,
    # inconvenient, needs repair, bad condition, incomplete
    # --------------------------------------------------------
    ("The road near our house has potholes that damage vehicles regularly", "medium"),
    ("water supply is very irregular and comes only for one hour a day", "medium"),
    ("Street lights are not working and the area is dark at night", "medium"),
    ("Garbage has not been collected for one week and is piling up", "medium"),
    ("The water pressure is too low and we cannot use it properly", "medium"),
    ("Power cuts are happening frequently without any notice", "medium"),
    ("The drainage is partially blocked and water flows slowly", "medium"),
    ("road construction is incomplete and has been left for two months", "medium"),
    ("The public toilet is very dirty and needs urgent cleaning", "medium"),
    ("water meter is broken and we are getting wrong bills", "medium"),
    ("The electricity transformer makes loud noise at night", "medium"),
    ("Park equipment is broken and needs replacement soon", "medium"),
    ("road markings have faded and are not visible during rain", "medium"),
    ("water comes with bad smell and we cannot drink it", "medium"),
    ("The community hall roof leaks during rain and damages property", "medium"),
    ("Garbage collection schedule is not being followed consistently", "medium"),
    ("electricity voltage fluctuates and damages household appliances", "medium"),
    ("The road to the market is always muddy and very inconvenient", "medium"),
    ("Sewage drain is partially clogged and overflows during heavy rain", "medium"),
    ("Street sign is damaged and difficult to read", "medium"),

    # --------------------------------------------------------
    # low priority
    # Signal words: minor, small, cosmetic, suggestion, faded,
    # slightly, could be better, not urgent, over time
    # --------------------------------------------------------
    ("The paint on the public wall has faded and looks old", "low"),
    ("A small crack appeared on the footpath but it is still walkable", "low"),
    ("The park bench has a loose screw and wobbles slightly", "low"),
    ("The road sign is slightly tilted but still readable", "low"),
    ("The public garden could use more trees and plants", "low"),
    ("Street light turns on a little late every evening", "low"),
    ("The bus shelter paint is peeling off slowly", "low"),
    ("A minor pothole appeared on a side road rarely used", "low"),
    ("The community notice board needs a fresh coat of paint", "low"),
    ("water supply timing could be more regular but it is manageable", "low"),
    ("The playground grass area needs mowing and looks overgrown", "low"),
    ("The dustbin near the park is getting full every few days", "low"),
    ("The road shoulder has minor erosion but main road is fine", "low"),
    ("Public garden benches could use repainting they look worn", "low"),
    ("The drainage grate has a small gap but functions normally", "low"),
    ("A streetlight flickers occasionally but mostly works fine", "low"),
    ("The ward office entrance steps have minor wear on edges", "low"),
    ("Minor water discoloration occasionally but clears after running tap", "low"),
    ("The public clock is running a few minutes slow", "low"),
    ("electricity meter box cover is slightly broken but meter works fine", "low"),
]
